[package]
org = "wso2"
name = "agent"
version = "0.1.0"

[build-options]
sticky = true

[[tool.openapi]]
id = "hotelSearchApi"
targetModule = "hotelSearchApi"
filePath = "../../resources/search_api_spec.yaml"

[[tool.openapi]]
id = "bookingApi"
targetModule = "bookingApi"
filePath = "../../resources/booking_api_spec.yaml"
